language: node_js
node_js:
- '11'
script:
- npm run build
deploy:
  provider: pages
  local_dir: ./client/dist
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  fqdn: madeitfor.fun
  on:
    branch: master