name = "www"
type = "webpack"
account_id = "c23e8e6efebf3303153d65a556df5bc8"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv-namespaces = [
  { binding = "db", id = "1f78c527740146e9a05fe5e8bddbebdf" }
]
vars = {MODE = "dev"}

[site]
bucket = "./static"
entry-point = "./static-site"

[env.prod]
vars = {MODE = "prod"}
kv-namespaces = [
  { binding = "db", id = "3cad38b1a6fe4f9ea58296bc3b0ac1a2" }
]