name = "www"
type = "webpack"
account_id = "c23e8e6efebf3303153d65a556df5bc8"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv-namespaces = [
  { binding = "db", id = "3cad38b1a6fe4f9ea58296bc3b0ac1a2" }
]